apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: postgraphile
  name: postgraphile
  namespace: postgraphile
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/component: postgraphile
