apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: node
  name: node
  namespace: villas
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: node
  template:
    metadata:
      labels:
        app.kubernetes.io/component: node
    spec:
      imagePullSecrets:
      - name: paoacr-credentials
      containers:
      - name: node
        image: priv-cr-sogno.some-priv-cr.io/sogno/villas-node:latest
        args:
        - node
        - /etc/villas/node/test.conf
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
        - containerPort: 12008
          protocol: UDP
        - containerPort: 12009
          protocol: UDP
        - containerPort: 12010
          protocol: UDP
        - containerPort: 12011
          protocol: UDP
        - containerPort: 12012
          protocol: UDP
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/villas/node/
          name: config
        - mountPath: /data
          name: data
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: node-config
      - name: data
        persistentVolumeClaim:
          claimName: node-data
