apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        # tls: true
        # authentication:
        #   type: scram-sha-512
        tls: false
        # type: nodeport
        # configuration:
        #   bootstrap:
        #     nodePort: 32100
        #   brokers:
        #   - broker: 0
        #     nodePort: 32000
        #   - broker: 1
        #     nodePort: 32001
        #   - broker: 2
        #     nodePort: 32002
    storage:
      type: persistent-claim
      size: 5Gi
      class: managed-nfs-storage
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      class: managed-nfs-storage
  entityOperator:
    topicOperator: {}
    userOperator: {}
